USE userdata;

DROP TABLE IF EXISTS TODOITEM;
DROP TABLE IF EXISTS USERINFO;
DROP TABLE IF EXISTS SESSION;

CREATE TABLE USERINFO (
	uid VARCHAR(25) PRIMARY KEY,
    name VARCHAR(64),
    given_name VARCHAR(64),
    email VARCHAR(64),
    signup_datetime DATETIME
);

/*CREATE TABLE SESSION (
	sid CHAR(40) PRIMARY KEY,
    uid VARCHAR(25) UNIQUE NOT NULL,
    timeout DATETIME NOT NULL,
    
    FOREIGN KEY (uid)
    REFERENCES USERINFO(uid) ON UPDATE CASCADE ON DELETE CASCADE
);*/
    
CREATE TABLE TODOITEM (
	id INT PRIMARY KEY AUTO_INCREMENT,
	uid VARCHAR(25),
    title VARCHAR(128) NOT NULL,
    tags VARCHAR(128),
    deadline VARCHAR(32),
    is_repeated BOOLEAN,
    repetition_id INT,
    memo VARCHAR(1024),
    status VARCHAR(32),
    
    FOREIGN KEY (uid)
    REFERENCES USERINFO(uid) ON UPDATE CASCADE ON DELETE CASCADE
);