USE userdata;

DROP TABLE IF EXISTS TODOITEMS;
DROP TABLE IF EXISTS USERINFO;

CREATE TABLE USERINFO (
	uid VARCHAR(25) PRIMARY KEY,
    name VARCHAR(64),
    given_name VARCHAR(64),
    email VARCHAR(64),
    signup_datetime DATETIME
);
    
CREATE TABLE TODOITEMS (
	uid VARCHAR(25) PRIMARY KEY,
    FOREIGN KEY (uid)
    REFERENCES USERINFO(uid) ON UPDATE CASCADE ON DELETE CASCADE
);